### ISSUE TITLE
Create Maskify Function

### ISSUE THREAD

**Issue by mkdika** [mkdika/jeneric#1]
Create new function, Maskify, within `StringFun` class.

- Function must have 2 arguments, 1. original string, 2. number of digits to masking (0 = all)
- Masked digits are from left to right.
- Use '*' as masking character.

Read [Contributing Guide](https://github.com/mkdika/jeneric/blob/master/docs/CONTRIBUTING.md) before start.

Thank you :heart:

**Comment by paynemiller92** [comment]
I'll take this one up.

**Comment by mkdika** [comment]
> I'll take this one up.

Hi @paynemiller92 , I am appologize, but this Issue has been taken and PR by @desdulianto .
I will release another issues later in Hacktoberfest period.

Thank you.

**Comment by mkdika** [comment]
Close issue by PR #2
